swagger: '2.0'
info:
  version: 1.0.0
  title: FoodTrackerServer
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  '/ServerMeals/{id}':
    get:
      tags:
        - ServerMeal
      summary: 'Find a model instance by {{id}}'
      operationId: ServerMeal.findOne
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/ServerMeal'
      deprecated: false
    put:
      tags:
        - ServerMeal
      summary: Put attributes for a model instance and persist it
      operationId: ServerMeal.replace
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: true
          schema:
            $ref: '#/definitions/ServerMeal'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/ServerMeal'
      deprecated: false
    patch:
      tags:
        - ServerMeal
      summary: Patch attributes for a model instance and persist it
      operationId: ServerMeal.update
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: true
          schema:
            $ref: '#/definitions/ServerMeal'
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/ServerMeal'
      deprecated: false
    delete:
      tags:
        - ServerMeal
      summary: 'Delete a model instance by {{id}}'
      operationId: ServerMeal.delete
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
  /ServerMeals:
    post:
      tags:
        - ServerMeal
      summary: Create a new instance of the model and persist it
      operationId: ServerMeal.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: true
          schema:
            $ref: '#/definitions/ServerMeal'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/ServerMeal'
      deprecated: false
    get:
      tags:
        - ServerMeal
      summary: Find all instances of the model
      operationId: ServerMeal.findAll
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/ServerMeal'
      deprecated: false
    delete:
      tags:
        - ServerMeal
      summary: Delete all instances of the model
      operationId: ServerMeal.deleteAll
      responses:
        '200':
          description: Request was successful
      deprecated: false
definitions:
  ServerMeal:
    properties:
      id:
        type: string
      name:
        type: string
      photo:
        type: string
      rating:
        type: number
    additionalProperties: false
    required:
      - name
      - photo
      - rating
